# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-03 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品种类', 'verbose_name_plural': '商品种类'},
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='df_goods_type',
        ),
    ]
